"""initial schema

Revision ID: afc9036d5272
Revises: 
Create Date: 2026-09-02 18:56:37.171524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afc9036d5272'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_uuid', sa.Text(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Double(), nullable=True),
    sa.Column('body_fat_pct', sa.Double(), nullable=True),
    sa.Column('body_fat_mass_kg', sa.Double(), nullable=True),
    sa.Column('skeletal_muscle_mass_kg', sa.Double(), nullable=True),
    sa.Column('skeletal_muscle_pct', sa.Double(), nullable=True),
    sa.Column('fat_free_mass_kg', sa.Double(), nullable=True),
    sa.Column('fat_free_pct', sa.Double(), nullable=True),
    sa.Column('total_body_water_kg', sa.Double(), nullable=True),
    sa.Column('basal_metabolic_rate_kcal', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_measurement_measured_at'), 'body_measurement', ['measured_at'], unique=False)
    op.create_index(op.f('ix_body_measurement_source_uuid'), 'body_measurement', ['source_uuid'], unique=True)
    op.create_table('ingestion_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='ingestion_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_entry',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_uuid', sa.Text(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meal_type', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.Text(), nullable=False),
    sa.Column('amount', sa.Double(), nullable=True),
    sa.Column('unit_code', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_entry_consumed_at'), 'nutrition_entry', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_nutrition_entry_meal_type'), 'nutrition_entry', ['meal_type'], unique=False)
    op.create_index(op.f('ix_nutrition_entry_source_uuid'), 'nutrition_entry', ['source_uuid'], unique=True)
    op.create_table('phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('FREE', 'BULK', 'CUT', 'MAINTAIN', name='phase_kind'), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('weight_target_kg', sa.Double(), nullable=True),
    sa.Column('body_fat_target_pct', sa.Double(), nullable=True),
    sa.Column('skeletal_muscle_target_kg', sa.Double(), nullable=True),
    sa.Column('daily_calories_target', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_on >= starts_on', name='ck_phase_dates_ordered'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phase_ends_on'), 'phase', ['ends_on'], unique=False)
    op.create_index(op.f('ix_phase_starts_on'), 'phase', ['starts_on'], unique=False)
    op.create_table('photo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256'),
    sa.UniqueConstraint('taken_on', 'tag', name='uq_photo_date_tag')
    )
    op.create_index(op.f('ix_photo_tag'), 'photo', ['tag'], unique=False)
    op.create_index(op.f('ix_photo_taken_on'), 'photo', ['taken_on'], unique=False)
    op.create_table('workout',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_uuid', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('sport_type', sa.Integer(), nullable=True),
    sa.Column('sport', sa.Text(), nullable=False),
    sa.Column('distance_m', sa.Double(), nullable=True),
    sa.Column('calories_kcal', sa.Double(), nullable=True),
    sa.Column('mean_heart_rate', sa.Double(), nullable=True),
    sa.Column('max_heart_rate', sa.Double(), nullable=True),
    sa.Column('min_heart_rate', sa.Double(), nullable=True),
    sa.Column('mean_speed_mps', sa.Double(), nullable=True),
    sa.Column('max_speed_mps', sa.Double(), nullable=True),
    sa.Column('mean_cadence', sa.Double(), nullable=True),
    sa.Column('max_cadence', sa.Double(), nullable=True),
    sa.Column('min_altitude_m', sa.Double(), nullable=True),
    sa.Column('max_altitude_m', sa.Double(), nullable=True),
    sa.Column('altitude_gain_m', sa.Double(), nullable=True),
    sa.Column('altitude_loss_m', sa.Double(), nullable=True),
    sa.Column('start_latitude', sa.Double(), nullable=True),
    sa.Column('start_longitude', sa.Double(), nullable=True),
    sa.Column('vo2_max', sa.Double(), nullable=True),
    sa.Column('sweat_loss_ml', sa.Double(), nullable=True),
    sa.Column('pool_length_m', sa.Double(), nullable=True),
    sa.Column('max_hr_custom', sa.SmallInteger(), nullable=True),
    sa.Column('max_hr_auto', sa.SmallInteger(), nullable=True),
    sa.Column('hr_aerobic_threshold', sa.SmallInteger(), nullable=True),
    sa.Column('hr_anaerobic_threshold', sa.SmallInteger(), nullable=True),
    sa.Column('resting_hr', sa.SmallInteger(), nullable=True),
    sa.Column('has_samples', sa.Boolean(), nullable=False),
    sa.Column('has_locations', sa.Boolean(), nullable=False),
    sa.Column('has_swim_lengths', sa.Boolean(), nullable=False),
    sa.Column('has_strength_sets', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_source_uuid'), 'workout', ['source_uuid'], unique=True)
    op.create_index(op.f('ix_workout_sport'), 'workout', ['sport'], unique=False)
    op.create_index(op.f('ix_workout_sport_type'), 'workout', ['sport_type'], unique=False)
    op.create_index(op.f('ix_workout_started_at'), 'workout', ['started_at'], unique=False)
    op.create_table('strength_set',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('idx', sa.SmallInteger(), nullable=False),
    sa.Column('duration_s', sa.Double(), nullable=True),
    sa.Column('reps', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.Double(), nullable=True),
    sa.Column('weight_unit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'idx')
    )
    op.create_table('swim_length',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('idx', sa.SmallInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('stroke_count', sa.SmallInteger(), nullable=True),
    sa.Column('stroke_type', sa.Text(), nullable=True),
    sa.Column('resting_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'idx')
    )
    op.create_index(op.f('ix_swim_length_stroke_type'), 'swim_length', ['stroke_type'], unique=False)
    op.create_table('workout_extra',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'kind', name='uq_workout_extra_kind')
    )
    op.create_index(op.f('ix_workout_extra_workout_id'), 'workout_extra', ['workout_id'], unique=False)
    op.create_table('workout_location',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('altitude_m', sa.Double(), nullable=True),
    sa.Column('accuracy_m', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'at')
    )
    op.create_index('ix_workout_location_at_brin', 'workout_location', ['at'], unique=False, postgresql_using='brin')
    op.create_table('workout_sample',
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('elapsed_ms', sa.BigInteger(), nullable=True),
    sa.Column('heart_rate', sa.SmallInteger(), nullable=True),
    sa.Column('speed_mps', sa.Double(), nullable=True),
    sa.Column('distance_m', sa.Double(), nullable=True),
    sa.Column('calories_kcal', sa.Double(), nullable=True),
    sa.Column('cadence', sa.SmallInteger(), nullable=True),
    sa.Column('segment', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'at')
    )
    op.create_index('ix_workout_sample_at_brin', 'workout_sample', ['at'], unique=False, postgresql_using='brin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_sample_at_brin', table_name='workout_sample', postgresql_using='brin')
    op.drop_table('workout_sample')
    op.drop_index('ix_workout_location_at_brin', table_name='workout_location', postgresql_using='brin')
    op.drop_table('workout_location')
    op.drop_index(op.f('ix_workout_extra_workout_id'), table_name='workout_extra')
    op.drop_table('workout_extra')
    op.drop_index(op.f('ix_swim_length_stroke_type'), table_name='swim_length')
    op.drop_table('swim_length')
    op.drop_table('strength_set')
    op.drop_index(op.f('ix_workout_started_at'), table_name='workout')
    op.drop_index(op.f('ix_workout_sport_type'), table_name='workout')
    op.drop_index(op.f('ix_workout_sport'), table_name='workout')
    op.drop_index(op.f('ix_workout_source_uuid'), table_name='workout')
    op.drop_table('workout')
    op.drop_index(op.f('ix_photo_taken_on'), table_name='photo')
    op.drop_index(op.f('ix_photo_tag'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_phase_starts_on'), table_name='phase')
    op.drop_index(op.f('ix_phase_ends_on'), table_name='phase')
    op.drop_table('phase')
    op.drop_index(op.f('ix_nutrition_entry_source_uuid'), table_name='nutrition_entry')
    op.drop_index(op.f('ix_nutrition_entry_meal_type'), table_name='nutrition_entry')
    op.drop_index(op.f('ix_nutrition_entry_consumed_at'), table_name='nutrition_entry')
    op.drop_table('nutrition_entry')
    op.drop_table('ingestion_run')
    op.drop_index(op.f('ix_body_measurement_source_uuid'), table_name='body_measurement')
    op.drop_index(op.f('ix_body_measurement_measured_at'), table_name='body_measurement')
    op.drop_table('body_measurement')
    # ### end Alembic commands ###
    # Les types ENUM natifs de PostgreSQL ne sont pas supprimés par
    # op.drop_table() : autogenerate ne les détecte pas automatiquement.
    # Sans ce nettoyage explicite, un downgrade suivi d'un upgrade échoue
    # avec "type already exists".
    postgresql.ENUM(name='phase_kind').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='ingestion_status').drop(op.get_bind(), checkfirst=True)
